export const userData = [
  {
    name: 'Ene',
    'Active User': 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: 'Feb',
    'Active User': 3000,
    pv: 1398,
    amt: 2210,
  },
  {
    name: 'Mar',
    'Active User': 2000,
    pv: 9800,
    amt: 2290,
  },
  {
    name: 'Apr',
    'Active User': 2780,
    pv: 3908,
    amt: 2000,
  },
  {
    name: 'May',
    'Active User': 1890,
    pv: 4800,
    amt: 2181,
  },
  {
    name: 'Jun',
    'Active User': 2390,
    pv: 3800,
    amt: 2500,
  },
  {
    name: 'Jul',
    'Active User': 3490,
    pv: 4300,
    amt: 2100,
  },
  {
    name: 'Ago',
    'Active User': 2200,
    pv: 4300,
    amt: 2100,
  },
  {
    name: 'Sep',
    'Active User': 960,
    pv: 4300,
    amt: 2100,
  },
  {
    name: 'Oct',
    'Active User': 5100,
    pv: 4300,
    amt: 2100,
  },
  {
    name: 'Nov',
    'Active User': 4750,
    pv: 4300,
    amt: 2100,
  },
  {
    name: 'Dic',
    'Active User': 2980,
    pv: 4300,
    amt: 2100,
  },
];

export const userRows = [
        { id: 1, username: 'Jon Snow', 
            avatar: 'https://indiehoy.com/wp-content/uploads/2020/06/jon-snow-1200x675.jpg', 
            email: 'jonsnow@gmail.com', 
            status: 'active', 
            transaction: '$120.000' },
        { id: 2, username: 'Cersei Lannister', 
            avatar: 'https://hips.hearstapps.com/es.h-cdn.co/fotoes/images/series-television/10-lecciones-de-cersei-lannister/137617982-1-esl-ES/10-lecciones-de-Cersei-Lannister.jpg', 
            email: 'cerseilennister@gmail.com', 
            status: 'active', 
            transaction: '$110.000' },
        { id: 3, username: 'Jaime Lannister', 
            avatar: 'https://elcomercio.pe/resizer/6j1gRP1bjUEhVvIChBn5v3Kme1U=/1200x1200/smart/filters:format(jpeg):quality(75)/arc-anglerfish-arc2-prod-elcomercio.s3.amazonaws.com/public/DTIMFKW5LVFCTIIXOB4BPYFEX4.jpg',
            email: 'jaimelannister@gmail.com', 
            status: 'active', 
            transaction: '$130.000' },
        { id: 4, username: 'Arya Stark', 
            avatar: 'https://www.quever.news/u/fotografias/m/2020/10/10/f850x638-1887_79376_4730.jpg', 
            email: 'aryastark@gmail.com', 
            status: 'active', 
            transaction: '$145.000' },
        { id: 5, username: 'Daenerys Targaryen', 
            avatar: 'https://pbs.twimg.com/profile_images/1243475459125456896/e-zIQiFY_400x400.jpg', 
            email: 'daenerystargaryen@gmail.com', 
            status: 'active', 
            transaction: '$112.000' },
        { id: 6, username: 'Melisandre', 
            avatar: 'https://img.europapress.es/fotoweb/fotonoticia_20160426100050_1200.jpg', 
            email: 'melisandre@gmail.com', 
            status: 'active', 
            transaction: '$176.000' },
        { id: 7, username: 'Ferrara Clifford', 
            avatar: 'https://cdn.theorg.com/c9440d58-4026-4544-a379-88a14fee3dfc_small.jpg', 
            email: 'ferraraclifford@gmail.com', 
            status: 'active', 
            transaction: '$190.000' },
        { id: 8, username: 'Rossini Frances', 
            avatar: 'https://c8.alamy.com/compes/rkw57p/antonio-gioachino-rossini-1792-1868-compositor-italiano-1862-etienne-carjat-frances-1828-1906-artista-etienne-carjat-origen-francia-fecha-rkw57p.jpg', 
            email: 'rossinifrances@gmail.com', 
            status: 'active', 
            transaction: '$90.000' },
        { id: 9, username: 'Harvey Roxie', 
            avatar: 'https://spoilertime.com/wp-content/uploads/2017/10/51007660.png-r_1920_1080-f_jpg-q_x-xxyxx.jpg', 
            email: 'harveyroxie@gmail.com', 
            status: 'active', 
            transaction: '$156.000' },
    ];
    
export const productsRows = [
        { id: 1, username: 'Jon Snow', 
            avatar: 'https://indiehoy.com/wp-content/uploads/2020/06/jon-snow-1200x675.jpg', 
            email: 'jonsnow@gmail.com', 
            status: 'active', 
            transaction: '$120.000' },
        { id: 2, username: 'Cersei Lannister', 
            avatar: 'https://hips.hearstapps.com/es.h-cdn.co/fotoes/images/series-television/10-lecciones-de-cersei-lannister/137617982-1-esl-ES/10-lecciones-de-Cersei-Lannister.jpg', 
            email: 'cerseilennister@gmail.com', 
            status: 'active', 
            transaction: '$110.000' },
        { id: 3, username: 'Jaime Lannister', 
            avatar: 'https://elcomercio.pe/resizer/6j1gRP1bjUEhVvIChBn5v3Kme1U=/1200x1200/smart/filters:format(jpeg):quality(75)/arc-anglerfish-arc2-prod-elcomercio.s3.amazonaws.com/public/DTIMFKW5LVFCTIIXOB4BPYFEX4.jpg',
            email: 'jaimelannister@gmail.com', 
            status: 'active', 
            transaction: '$130.000' },
        { id: 4, username: 'Arya Stark', 
            avatar: 'https://www.quever.news/u/fotografias/m/2020/10/10/f850x638-1887_79376_4730.jpg', 
            email: 'aryastark@gmail.com', 
            status: 'active', 
            transaction: '$145.000' },
        { id: 5, username: 'Daenerys Targaryen', 
            avatar: 'https://pbs.twimg.com/profile_images/1243475459125456896/e-zIQiFY_400x400.jpg', 
            email: 'daenerystargaryen@gmail.com', 
            status: 'active', 
            transaction: '$112.000' },
        { id: 6, username: 'Melisandre', 
            avatar: 'https://img.europapress.es/fotoweb/fotonoticia_20160426100050_1200.jpg', 
            email: 'melisandre@gmail.com', 
            status: 'active', 
            transaction: '$176.000' },
        { id: 7, username: 'Ferrara Clifford', 
            avatar: 'https://cdn.theorg.com/c9440d58-4026-4544-a379-88a14fee3dfc_small.jpg', 
            email: 'ferraraclifford@gmail.com', 
            status: 'active', 
            transaction: '$190.000' },
        { id: 8, username: 'Rossini Frances', 
            avatar: 'https://c8.alamy.com/compes/rkw57p/antonio-gioachino-rossini-1792-1868-compositor-italiano-1862-etienne-carjat-frances-1828-1906-artista-etienne-carjat-origen-francia-fecha-rkw57p.jpg', 
            email: 'rossinifrances@gmail.com', 
            status: 'active', 
            transaction: '$90.000' },
        { id: 9, username: 'Harvey Roxie', 
            avatar: 'https://spoilertime.com/wp-content/uploads/2017/10/51007660.png-r_1920_1080-f_jpg-q_x-xxyxx.jpg', 
            email: 'harveyroxie@gmail.com', 
            status: 'active', 
            transaction: '$156.000' },
    ];
